### ISSUE TITLE
Issue with tall portrait image

### ISSUE THREAD

**Issue by alastair-todd** [Mawi137/ngx-image-cropper#259]
I am surfacing the cropper in Material Dialog and have a div wrapping the cropper component which I've constrained to `400px x 300px`

All seems fine when using a landscape image, but when selecting portrait, it is being cropped on a vertical plane:

![image](https://user-images.githubusercontent.com/595192/73349832-d0d52500-4283-11ea-946d-62a2eb6e1bd8.png)

![image](https://user-images.githubusercontent.com/595192/73350149-6a9cd200-4284-11ea-85a6-e704a4e78aad.png)

```typescript

<form>
  <section class="section staff-image">
    <input type="file" (change)="fileChangeEvent($event)" accept=".jpg, .jpeg, .png" />

    <div class="image-crop">
      <image-cropper
        [imageChangedEvent]="imageChangedEvent"
        (imageCropped)="imageCropped($event)"
        (imageLoaded)="imageLoaded()"
        (cropperReady)="cropperReady()"
        (loadImageFailed)="loadImageFailed()"
        aspectRatio="1"
        format="png"
        cropperMinWidth="96"
        cropperMinHeight="96"
        resizeToWidth="96"
        resizeToHeight="96"
        roundCropper="true"
      ></image-cropper>

      <img [src]="croppedImage" class="output-thumbnail" />
    </div>
  </section>
</form>
```
```scss

form {
  height: 50rem;
  width: 60rem;
}
.image-crop {
  display: flex;
  flex-direction: row;
  width: 40rem;
  height: 30rem;

  .output-thumbnail {
    border-radius: 100%;
    max-width: 9.6rem;
    max-height: 9.6rem;
  }
}

```

![pexels-photo-774909](https://user-images.githubusercontent.com/595192/73350228-8f914500-4284-11ea-93a2-589503cf7d0b.jpeg)
