### ISSUE TITLE
Set border of Cropper to hide

### ISSUE THREAD

**Issue by shahmeet999** [Mawi137/ngx-image-cropper#265]
How can I hide the cropper border and set to display none in the image cropper ???

**Comment by willKo** [comment]
If you want to remove the white `outline`, you could add this to your style.css file: 

```css
image-cropper div .overlay {
  outline: none !important;
}
```

Not sure if this works always. 
I know it is not nice, and also very bad to write / maintain if you have multiple style changes.

I would be greatful if someone know a nicer / easier way to customize the styling.
